name: testvalley
description: A new Flutter project.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: '>=3.2.6 <4.0.0'

dependencies:
  intl: any
  get: ^4.6.6
  timeago: ^3.6.1
  shimmer: ^3.0.0
  flutter_svg: ^2.0.9
  google_fonts: ^4.0.4
  sendbird_sdk: ^3.2.19
  flutter_dotenv: ^5.1.0
  flutter_spinkit: ^5.2.0
  cupertino_icons: ^1.0.6
  flutter_animate: ^4.5.0
  flutter_screenutil: ^5.9.0
  cached_network_image: ^3.3.1
  flutter_native_splash: ^2.3.10

  flutter:
    sdk: flutter

dev_dependencies:
  flutter_lints: ^3.0.1
  flutter_launcher_icons: ^0.13.1

  flutter_test:
    sdk: flutter


flutter:
  uses-material-design: true

  assets:
    - .env
    - assets/icons/
    - assets/images/